In [1]:
import numpy as np

In [30]:
mat1=[[1,2,3],[4,5,6],[7,8,9]]

In [36]:
np.array(mat1) # np.array creates a copy and doesn't modify the main var - np.asarray doesn't, and can modify the var
# np.array(mat1)[0,1]=100 deosn't change the element [0,1], because it creats a copy
# np.asarray(mat1)[0,1]=100 will actually replace the element [0,1] with the avlue 100

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
np.array(mat1)[0,1]

2

In [38]:
np.zeros((2,3)) # Also np.ones((3,4))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [39]:
np.arange(0,10,1) # DOESN'T include the 2nd arg # The 3rd arg is the lenght of spacing btw numbers

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
np.linspace(0,10,11) # DOES include the 2nd arg  # The 3rd arg is the number of evenly spaced numbers

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [42]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
np.random.rand(5) # Random distribution, between [0,1]

array([0.57208604, 0.93114159, 0.14777287, 0.79733121, 0.91824961])

In [31]:
np.random.randn(5) # Normal or gausian distribution (distribution that's centered around zero)

array([ 1.14750365,  0.34004735, -0.72560836, -1.99442159, -1.01814561])

In [49]:
arr = np.arange(0,25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [50]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [51]:
ranarr=np.random.randint(0,50,20)
ranarr

array([39,  5, 20, 29,  4, 48,  6, 47, 41, 33, 36, 44,  1, 44, 40, 33, 11,
       27, 40, 43])

In [56]:
ranarr.max()

48

In [55]:
ranarr.argmax()

5

In [70]:
ar2=ranarr.copy()[0:10]
ar2

array([39,  5, 20, 29,  4, 48,  6, 47, 41, 33])

In [61]:
import copy ; ar2=copy.deepcopy(ranarr[0:10])
ar2

array([39,  5, 20, 29,  4, 48,  6, 47, 41, 33])

In [62]:
ar3=ranarr.copy()[0:10]
ar3

array([39,  5, 20, 29,  4, 48,  6, 47, 41, 33])

In [63]:
varr=np.array([[2,5,3],[65,76,2],[23,0,12]])
varr

array([[ 2,  5,  3],
       [65, 76,  2],
       [23,  0, 12]])

In [64]:
ar3

array([39,  5, 20, 29,  4, 48,  6, 47, 41, 33])

In [65]:
ar3>4

array([ True,  True,  True,  True, False,  True,  True,  True,  True,
        True])

In [74]:
b_a = ar3 > 10

In [75]:
b_a

array([ True, False,  True,  True, False,  True, False,  True,  True,
        True])

In [79]:
b_a.dtype

dtype('bool')

In [77]:
ar3[ar3>10]

array([39, 20, 29, 48, 47, 41, 33])

In [78]:
ar3[b_a]

array([39, 20, 29, 48, 47, 41, 33])

In [80]:
arr=np.arange(1,50)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [81]:
arr=np.arange(1,51).reshape(5,10)
arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [58]:
ar3

array([19,  9,  0,  5,  7,  5, 39, 24,  8, 30])

In [61]:
np.sqrt(ar3)

array([4.35889894, 3.        , 0.        , 2.23606798, 2.64575131,
       2.23606798, 6.244998  , 4.89897949, 2.82842712, 5.47722558])